set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins/'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'moon'
set -g @rose_pine_host 'on'
set -g @rose_pine_user 'on'

run '~/.local/share/tmux/plugins/tpm/tpm'
