set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_variant 'main'

set -g @rose_pine_host 'on' # Enables hostname in the status bar
set -g @rose_pine_user 'on' # Turn on the username component in the statusbar

set -g @plugin '27medkamal/tmux-session-wizard'

run '~/.tmux/plugins/tpm/tpm'
